{
    "affected": [
        {
            "package": {
                "ecosystem": "Photon OS:4.0",
                "name": "python3-certifi",
                "purl": "pkg:rpm/vmware/python3-certifi?distro=photon-4"
            }
        },
        {
            "package": {
                "ecosystem": "Photon OS:4.0",
                "name": "python3-certifi",
                "purl": "pkg:rpm/vmware/python3-certifi?distro=photon-4"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "2023.11.17-1.ph4"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        },
        {
            "package": {
                "ecosystem": "Photon OS:4.0",
                "name": "python3-certifi",
                "purl": "pkg:rpm/vmware/python3-certifi?distro=photon-4"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "introduced": "0"
                        },
                        {
                            "fixed": "2023.11.17-1.ph4"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        }
    ],
    "id": "PHSA-2023-4.0-0534",
    "modified": "2025-01-24T05:27:06Z",
    "published": "2023-12-24T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-4.0-534"
        }
    ],
    "related": [
        "CVE-2022-23491",
        "CVE-2023-37920"
    ]
}