{
    "affected": [
        {
            "package": {
                "ecosystem": "photon:3.0",
                "name": "yarn",
                "purl": "pkg:rpm/vmware/yarn?distro=photon-3"
            }
        },
        {
            "package": {
                "ecosystem": "photon:3.0",
                "name": "nginx",
                "purl": "pkg:rpm/vmware/nginx?distro=photon-3"
            }
        },
        {
            "package": {
                "ecosystem": "photon:3.0",
                "name": "libsolv",
                "purl": "pkg:rpm/vmware/libsolv?distro=photon-3"
            }
        },
        {
            "package": {
                "ecosystem": "photon:3.0",
                "name": "python2",
                "purl": "pkg:rpm/vmware/python2?distro=photon-3"
            }
        },
        {
            "package": {
                "ecosystem": "photon:3.0",
                "name": "bash",
                "purl": "pkg:rpm/vmware/bash?distro=photon-3"
            }
        }
    ],
    "id": "PHSA-2020-3.0-0057",
    "modified": "2023-03-16T05:25:30Z",
    "published": "2019-03-06T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-3.0-3"
        }
    ],
    "related": [
        "CVE-2019-20372",
        "CVE-2019-9674",
        "CVE-2019-20387",
        "CVE-2019-10773",
        "CVE-2019-18276"
    ]
}