{
    "affected": [
        {
            "package": {
                "ecosystem": "Photon OS:3.0",
                "name": "python-certifi",
                "purl": "pkg:rpm/vmware/python-certifi?distro=photon-3"
            }
        },
        {
            "package": {
                "ecosystem": "Photon OS:3.0",
                "name": "python-certifi",
                "purl": "pkg:rpm/vmware/python-certifi?distro=photon-3"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "2023.11.17-1.ph3"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        },
        {
            "package": {
                "ecosystem": "Photon OS:3.0",
                "name": "python-certifi",
                "purl": "pkg:rpm/vmware/python-certifi?distro=photon-3"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "introduced": "0"
                        },
                        {
                            "fixed": "2023.11.17-1.ph3"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        }
    ],
    "id": "PHSA-2023-3.0-0704",
    "modified": "2025-01-24T05:27:06Z",
    "published": "2023-12-26T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-3.0-704"
        }
    ],
    "related": [
        "CVE-2023-37920",
        "CVE-2022-23491"
    ]
}