{
    "affected": [
        {
            "package": {
                "ecosystem": "Photon OS:2.0",
                "name": "python3",
                "purl": "pkg:rpm/vmware/python3?distro=photon-2"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "3.6.9-14.ph2"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        },
        {
            "package": {
                "ecosystem": "Photon OS:2.0",
                "name": "python3",
                "purl": "pkg:rpm/vmware/python3?distro=photon-2"
            },
            "ranges": [
                {
                    "events": [
                        {
                            "introduced": "0"
                        },
                        {
                            "fixed": "3.6.9-14.ph2"
                        }
                    ],
                    "type": "ECOSYSTEM"
                }
            ]
        }
    ],
    "id": "PHSA-2022-0516",
    "modified": "2025-01-24T05:27:06Z",
    "published": "2022-09-15T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-2.0-516"
        }
    ],
    "related": [
        "CVE-2021-28861",
        "CVE-2021-4189"
    ]
}