{
    "affected": [
        {
            "package": {
                "ecosystem": "photon:3.0",
                "name": "PyYAML",
                "purl": "pkg:rpm/vmware/PyYAML?distro=photon-3"
            }
        },
        {
            "package": {
                "ecosystem": "photon:3.0",
                "name": "file",
                "purl": "pkg:rpm/vmware/file?distro=photon-3"
            }
        },
        {
            "package": {
                "ecosystem": "photon:3.0",
                "name": "postgresql",
                "purl": "pkg:rpm/vmware/postgresql?distro=photon-3"
            }
        },
        {
            "package": {
                "ecosystem": "photon:3.0",
                "name": "gnupg",
                "purl": "pkg:rpm/vmware/gnupg?distro=photon-3"
            }
        },
        {
            "package": {
                "ecosystem": "photon:3.0",
                "name": "gnutls",
                "purl": "pkg:rpm/vmware/gnutls?distro=photon-3"
            }
        }
    ],
    "id": "PHSA-2020-3.0-0080",
    "modified": "2023-03-16T05:25:30Z",
    "published": "2019-03-06T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-3.0-3"
        }
    ],
    "related": [
        "CVE-2019-14855",
        "CVE-2019-8907",
        "CVE-2019-8905",
        "CVE-2019-8906",
        "CVE-2020-1747",
        "CVE-2020-11501",
        "CVE-2019-8904",
        "CVE-2020-1720"
    ]
}