{
    "affected": [
        {
            "package": {
                "ecosystem": "photon:4.0",
                "name": "containerd",
                "purl": "pkg:rpm/vmware/containerd?distro=photon-4"
            }
        },
        {
            "package": {
                "ecosystem": "photon:4.0",
                "name": "python3",
                "purl": "pkg:rpm/vmware/python3?distro=photon-4"
            }
        },
        {
            "package": {
                "ecosystem": "photon:4.0",
                "name": "cups",
                "purl": "pkg:rpm/vmware/cups?distro=photon-4"
            }
        },
        {
            "package": {
                "ecosystem": "photon:4.0",
                "name": "u-boot",
                "purl": "pkg:rpm/vmware/u-boot?distro=photon-4"
            }
        }
    ],
    "id": "PHSA-2023-4.0-0329",
    "modified": "2023-03-16T05:25:30Z",
    "published": "2021-03-12T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-4.0-4"
        }
    ],
    "related": [
        "CVE-2022-23471",
        "CVE-2018-4300",
        "CVE-2022-26691",
        "CVE-2020-10735",
        "CVE-2022-2347"
    ]
}