{
    "affected": [
        {
            "package": {
                "ecosystem": "photon:4.0",
                "name": "python3",
                "purl": "pkg:rpm/vmware/python3?distro=photon-4"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "3.10.0-7.ph4"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        },
        {
            "package": {
                "ecosystem": "photon:4.0",
                "name": "curl",
                "purl": "pkg:rpm/vmware/curl?distro=photon-4"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "7.83.1-3.ph4"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        },
        {
            "package": {
                "ecosystem": "photon:4.0",
                "name": "gnutls",
                "purl": "pkg:rpm/vmware/gnutls?distro=photon-4"
            },
            "ranges": {
                "events": [
                    {
                        "introduced": "0"
                    },
                    {
                        "fixed": "3.7.1-4.ph4"
                    }
                ],
                "type": "ECOSYSTEM"
            }
        }
    ],
    "id": "PHSA-2022-4.0-0240",
    "modified": "2023-04-30T05:25:37Z",
    "published": "2022-09-05T00:00:00Z",
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://github.com/vmware/photon/wiki/Security-Update-4.0-240"
        }
    ],
    "related": [
        "CVE-2022-35252",
        "CVE-2021-28861",
        "CVE-2021-4209"
    ]
}